config/routes.rb
Rails.application.routes.draw do

  root 'utilisateurs#index'

  resources :utilisateurs
  post 'connexion' => 'utilisateurs#login'
  get 'deconnexion' => 'utilisateurs#logout'
  get 'changePassword' => 'utilisateurs#change_password'
  post 'submitNewPassword' => 'utilisateurs#submit_password_change'
  get '/list' => 'utilisateurs#list', :as => 'utilisateurs_list'
  get 'confirm/:id' => 'utilisateurs#confirm', :as => 'utilisateurs_confirm'
  get 'confirm_admin/:id' => 'utilisateurs#confirm_admin'
  get 'enseignants' => 'utilisateur#index'
  get 'etudiants' => 'utilisateurs#index'

  resources :matieres
  get 'add_etu' => 'matieres#add_student'
  post 'submit_etu' => 'matieres#submit_student'

  get 'sendConfirmEmail' => 'appartenances#invite'
  post 'appartenances/createList' => 'appartenances#createList'

  resources :epreuves
  get 'matieres/:matiere_id/epreuves' => 'epreuves#index_by', :as => 'epreuves_by_matiere'
  post 'epreuves/set_matiere' => 'epreuves#set_matiere'

  get 'resultats/create' => 'resultats#create'
  get 'epreuves/:epreuve_id/resultats' => 'resultats#show', :as => 'resultats_show'
  post 'resultats/update' => 'resultats#update', :as => 'resultats_update'
  
  

end

app/models/utilisateur.rb
class Utilisateur < ActiveRecord::Base

	has_secure_password

	validates :nom, :presence => true
	validates :prenom, :presence => true
	validates :email, :presence => true, :uniqueness => true
	validates :password, :presence => true, :if => :password

	def fullname
		return prenom.to_s + " " + nom.to_s
	end
end

app/controllers/utilisateurs_controller.rb
require 'securerandom'
require 'bcrypt'

class UtilisateursController < ApplicationController
  before_action :set_utilisateur, only: [:show, :edit, :update, :destroy]

  # GET /utilisateurs
  # GET /utilisateurs.json
  def index
    if isConnected?
      @utilisateur = current_user
    end
  end

  # GET /utilisateurs/1
  # GET /utilisateurs/1.json
  def show
  end

  # GET /utilisateurs/new
  def new
    @utilisateur = Utilisateur.new
    if (params[:type] == 'Etudiant')
      @password = SecureRandom.base64(10)  
    end
    @utilisateur.type = params[:type]  
  end



  # GET /utilisateurs/1/edit
  def edit
  end

  def list
    if isConnected? && current_user.type == 'Admin'
      @utilisateurs = Utilisateur.all.sort_by{|user| [user.type, user.nom]}
      @utilisateur = current_user
    else
      redirect_to root_path
    end
  end

  # POST /utilisateurs
  # POST /utilisateurs.json
  def create
    @password = params[:utilisateur][:password]
    if params[:utilisateur][:type]
      @utilisateur = Enseignant.new(utilisateur_params)
    else
      @utilisateur = Etudiant.new(utilisateur_params)
    end
    @utilisateur.etat = 'pending'
    respond_to do |format|
      if @utilisateur.save
        if @utilisateur.type == 'Enseignant'
          format.html { redirect_to root_path, notice: 'Votre compte a été créé. Toutefois, un admin doit le valider.' }
          format.json { render :show, status: :created, location: root_path }
        else
          format.html { redirect_to sendConfirmEmail_path(:matiere_id => current_matiere.id, :etudiant_id => @utilisateur.id, :temp_password => @password) }
          format.json { render :show, status: :created, location: matieres_path }
        end
      else
        format.html { render :new }
        format.json { render json: @utilisateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /utilisateurs/1
  # PATCH/PUT /utilisateurs/1.json
  def update
    respond_to do |format|
      if @utilisateur.update(utilisateur_params)
        format.html { redirect_to @utilisateur, notice: 'Utilisateur was successfully updated.' }
        format.json { render :show, status: :ok, location: @utilisateur }
      else
        format.html { render :edit }
        format.json { render json: @utilisateur.errors, status: :unprocessable_entity }
      end
    end
  end

  def login
    if (user = Utilisateur.find_by(email: params[:email])) != nil
      if user.authenticate(params[:password])
        if user.etat != 'pending'
          session[:current_user_id] = user.id
          flash[:alert] = 'Vous êtes connecté.'
          redirect_to root_path
        else
          flash[:alert] = 'Votre compte n\'a pas encore été activé'
          redirect_to root_path
        end
      else
        flash[:alert] = 'Mauvais identifiant ou mot de passe'
        redirect_to root_path
      end
    else
      flash[:alert] = 'Mauvais identifiant ou mot de passe'
      redirect_to root_path
    end
  end

  def logout
    session.destroy
    respond_to do |format|
      format.html{ redirect_to "/", alert: 'Vous vous êtes déconnectés' }
    end
  end

  def change_password
  end

  def submit_password_change
    @utilisateur = current_user
    if @utilisateur.authenticate(params[:old_password])
      @utilisateur.update(:password => params[:new_password], :password_confirmation => params[:new_password_confirmation])
      respond_to do |format|
        format.html{ redirect_to root_path, notice: 'Mot de passe changé avec succès'}
      end
    else
      respond_to do |format|
        format.html{ redirect_to root_path, notice: 'Mot de passe incorrect'}
      end
    end
  end

  def confirm
    @utilisateurs = Utilisateur.all
    @utilisateur = Utilisateur.find(params[:id])
    @utilisateur.update_attribute('etat', 'validé')
    respond_to do |format|
      format.html{ redirect_to root_path, notice: 'Vous pouvez désormais vous connecter au site grâce à votre email'}
    end
  end

  def confirm_admin
    @utilisateurs = Utilisateur.all
    @utilisateur = Utilisateur.find(params[:id])
    respond_to do |format|
      if @utilisateur.update_attribute('etat', 'validé')
        format.html{ redirect_to utilisateurs_list_path, notice: 'Utilisateur validé'}
      else
        format.html { render :list }
      end
    end
  end

  # DELETE /utilisateurs/1
  # DELETE /utilisateurs/1.json
  def destroy
    if @utilisateur.type == 'Enseignant'
      @utilisateur.matieres.each do |m|
        m.destroy
      end
    elsif @utilisateur.type == 'Etudiant'
      @utilisateur.appartenances.each do |a|
        a.destroy
      end
      @utilisateur.resultats.each do |res|
        res.destroy
      end
    else
      respond_to do |format|
        format.html { redirect_to utilisateurs_list_path, notice: 'Impossible de supprimer un compte admin' }
        format.json { head :no_content }
      end
    end
    @utilisateur.destroy
    respond_to do |format|
      format.html { redirect_to utilisateurs_list_path, notice: 'Utilisateur supprimé avec succès' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_utilisateur
      @utilisateur = Utilisateur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def utilisateur_params
      allow = [:nom, :prenom, :email, :password, :password_confirmation, :type]
      params.require(:utilisateur).permit(allow)
    end
end

app/helpers/utilisateurs_helper.rb
module UtilisateursHelper
end

app/views/utilisateurs/_form.html.erb
<%= form_for(@utilisateur) do |f| %>
  <% if @utilisateur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@utilisateur.errors.count, "error") %> prohibited this utilisateur from being saved:</h2>
      <ul>
      <% @utilisateur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">

    <table>
      <% if @utilisateur.type == 'Enseignant' %>   
        <tr><td><label for="utilisateur_nom">Nom: </label><br>
        <%= text_field 'utilisateur', 'nom' %></tr></td>
        <tr><td><label for="utilisateur_prenom">Prenom: </label><br>
        <%= text_field 'utilisateur', 'prenom' %></tr></td>
        <tr><td><label for="utilisateur_email">Adresse email: </label><br>
        <%= email_field 'utilisateur', 'email' %></tr></td>
        <tr><td><label for="utilisateur_password">Mot de passe: </label><br>
        <%= password_field 'utilisateur', 'password' %></tr></td>
        <tr><td><label for="utilisateur_confirm_password">Confirmer le mot de passe: </label><br>
        <%= password_field 'utilisateur', 'password_confirmation' %></tr></td>
        <p><%= hidden_field 'utilisateur', 'type' %></p>
      <% else %>
        <tr><td><label for="utilisateur_nom">Nom: </label><br>
        <%= text_field 'utilisateur', 'nom' %></tr></td>
        <tr><td><label for="utilisateur_prenom">Prenom: </label><br>
        <%= text_field 'utilisateur', 'prenom' %></tr></td>
        <tr><td><label for="utilisateur_email">Adresse email: </label><br>
        <%= email_field 'utilisateur', 'email' %></tr></td>
        <p><%= hidden_field 'utilisateur', 'password', :value => @password %></p>
      <% end %>
    </table>
    <%= f.submit 'Valider' %>

  

  </div>

<% end %>

app/views/utilisateurs/change_password.html.erb
<h1>Changer de mot de passe</h1>
<div class="actions">
<table>
<%= form_tag(submitNewPassword_path) do %>
	<tr><td><label for="utilisateur_password">Mot de passe actuel: </label><br>
	<%= password_field_tag(:old_password) %></td></tr>
	<tr><td><label for="utilisateur_password_new">Nouveau mot de passe: </label><br>
	<%= password_field_tag(:new_password) %></td></tr>
	<tr><td><label for="utilisateur_password_new_confirm">Confirmer le nouveau mot de passe: </label><br>
	<%= password_field_tag(:new_password_confirmation) %></td></tr>
</table>
<%= submit_tag 'Valider' %>
<% end %>
</div>

app/views/utilisateurs/confirm.html.erb
<p>Vous pouvez désormais vous connecter au site grâce à votre email</p>

app/views/utilisateurs/edit.html.erb
<h1>Editing Utilisateur</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @utilisateur %> |
<%= link_to 'Retour', utilisateurs_path %>

app/views/utilisateurs/index.html.erb
<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<% if !@utilisateur %>

  <h1>Connexion</h1>

  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%= form_tag('/connexion') do %>
        <div class="actions">
          <p><label class="submit1" for="utilisateur_email">Adresse email: </label>
          <%= email_field_tag(:email) %></p>
          <p><label class="submit2" for="utilisateur_password">Mot de passe: </label>
          <%= password_field_tag(:password) %></p>
          <%= submit_tag 'Connexion' %>
          <%= link_to 'S\'inscrire', new_utilisateur_path(:type => 'Enseignant') %>
        </div>
      <% end %>
    </tbody>
  </table>

  <br>
<% else %>
<div class="actions">
  <p>Vous pouvez désormais naviguer sur le site !</p>
</div>
<% end %>

app/views/utilisateurs/list.html.erb
<p id="notice"><%= notice %></p>
<% if @utilisateur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@utilisateur.errors.count, "error") %> prohibited this utilisateur from being saved:</h2>
      <ul>
      <% @utilisateur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>
	<tr class="header">
		<th>Nom</th>
		<th>Prénom</th>
		<th>E-mail</th>
		<th>Type</th>
		<th>Statut</th>
		<th>Actions</th>
	</tr>
	<% @utilisateurs.each do |user| %>
		<tr>
			<td><%= user.nom %></td>
			<td><%= user.prenom %></td>
			<td><%= user.email %></td>
			<td><%= user.type %></td>
			<% if user.etat == 'pending' %>
				<td class="pending"><a href=<%='/confirm_admin/' + user.id.to_s%>><%= user.etat %></a></td>
			<% else %>
				<td class="activated"><%= user.etat %></td>
			<% end %>
			<% if user != current_user %>
				<td><%= link_to 'Supprimer', 'utilisateurs/' + user.id.to_s, method: :delete, data: { confirm: 'Etes vous sûr ?' } %></td>
			<% end %>
		</tr>
	<% end %>
</table>

app/views/utilisateurs/new.html.erb
<% if @utilisateur.type == 'Etudiant' %>
	<h1>Invitation</h1>
<% else %>
	<h1>Inscription</h1>
<% end %>

<%= render 'form' %>

<%= link_to 'Annuler', utilisateurs_path %>

app/views/utilisateurs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Modifier', edit_utilisateur_path(@utilisateur) %> |
<%= link_to 'Retour', utilisateurs_path %>