config/routes.rb
Rails.application.routes.draw do

  root 'utilisateurs#index'

  resources :utilisateurs
  post 'connexion' => 'utilisateurs#login'
  get 'deconnexion' => 'utilisateurs#logout'
  get 'changePassword' => 'utilisateurs#change_password'
  post 'submitNewPassword' => 'utilisateurs#submit_password_change'
  get '/list' => 'utilisateurs#list', :as => 'utilisateurs_list'
  get 'confirm/:id' => 'utilisateurs#confirm', :as => 'utilisateurs_confirm'
  get 'confirm_admin/:id' => 'utilisateurs#confirm_admin'
  get 'enseignants' => 'utilisateur#index'
  get 'etudiants' => 'utilisateurs#index'

  resources :matieres
  get 'add_etu' => 'matieres#add_student'
  post 'submit_etu' => 'matieres#submit_student'

  get 'sendConfirmEmail' => 'appartenances#invite'
  post 'appartenances/createList' => 'appartenances#createList'

  resources :epreuves
  get 'matieres/:matiere_id/epreuves' => 'epreuves#index_by', :as => 'epreuves_by_matiere'
  post 'epreuves/set_matiere' => 'epreuves#set_matiere'

  get 'resultats/create' => 'resultats#create'
  get 'epreuves/:epreuve_id/resultats' => 'resultats#show', :as => 'resultats_show'
  post 'resultats/update' => 'resultats#update', :as => 'resultats_update'
  
  

end

app/models/resultat.rb
class Resultat < ActiveRecord::Base
	belongs_to :epreuve
	belongs_to :etudiant

	validates :epreuve_id, :presence => "true"
	validates :etudiant_id, :presence => "true"
end

app/controllers/resultats_controller.rb
class ResultatsController < ApplicationController

	def create
		etu_ids = params[:etudiants_ids]
		if etu_ids != nil
			etu_ids.each do |id|
				@resultat = Resultat.new(:epreuve_id => current_epreuve.id, :etudiant_id => id)
				@resultat.save
			end
		end
		respond_to do |format|
			format.html { redirect_to epreuves_path, notice: 'L\'épreuve a été ajoutée avec succès.'}
			format.json { render :show, status: :created, location: epreuves_path }
		end

	end

	def show
		session[:current_epreuve_id] = params[:epreuve_id]
		@epreuve = current_epreuve
		@resultats = Resultat.where(epreuve_id: @epreuve.id)
	end

	def update
		@resultats = params[:resultats]
		@resultats.each do |couple|
			id, note = couple
			@resultat = Resultat.find(id)
			@resultat.update(:valeur => note)
		end
		respond_to do |format|
			format.html { redirect_to epreuves_path, notice: 'Notes enregistrées avec succès' }
        	format.json { render :show, status: :ok, location: epreuves_path }
    	end
	end

	private

	def resultats_params
		allow = [:epreuve_id, :etudiant_id]
		params.permit(allow)
	end
end

app/helpers/resultats_helper.rb
module ResultatsHelper
end

app/views/resultats/show.html.erb
<h1 class="titre">Résultats pour l'épreuve <%= @epreuve.matiere.titre %> | <%= @epreuve.titre %></h1>

<%= form_tag(resultats_update_path) do %>
	<table>
		<tr class="header">
			<th>Nom</th>
			<th>Prénom</th>
			<th>Note</th>
		</tr>
		<% @resultats.each do |res| %>
			<tr>
				<td><%= res.etudiant.nom %></td>
				<td><%= res.etudiant.prenom %></td>
				<% if res.valeur == nil %>
					<% if current_user.type == 'Etudiant' %>
						<td>Non publiée</td>
					<% else %>
						<td class="note"><%= number_field_tag "resultats[#{res.id}]", min: 0, max: 20 %></td>
					<% end %>
				<% else %>
					<% if current_user.type == 'Etudiant' %>
						<td class="note"><%= number_field_tag "resultats[#{res.id}]", "#{res.valeur}", disabled: true %></td>
					<% else %>
						<td class="note"><%= number_field_tag "resultats[#{res.id}]", "#{res.valeur}", min: 0, max: 20 %></td>
					<% end %>				
				<% end %>
			</tr>
		<% end %>
	</table>
	<% if current_user.type != 'Etudiant' %>
		<%= submit_tag 'Enregistrer' %>
	<% end %>
<% end %>