config/routes.rb
Rails.application.routes.draw do

  root 'utilisateurs#index'

  resources :utilisateurs
  post 'connexion' => 'utilisateurs#login'
  get 'deconnexion' => 'utilisateurs#logout'
  get 'changePassword' => 'utilisateurs#change_password'
  post 'submitNewPassword' => 'utilisateurs#submit_password_change'
  get '/list' => 'utilisateurs#list', :as => 'utilisateurs_list'
  get 'confirm/:id' => 'utilisateurs#confirm', :as => 'utilisateurs_confirm'
  get 'confirm_admin/:id' => 'utilisateurs#confirm_admin'
  get 'enseignants' => 'utilisateur#index'
  get 'etudiants' => 'utilisateurs#index'

  resources :matieres
  get 'add_etu' => 'matieres#add_student'
  post 'submit_etu' => 'matieres#submit_student'

  get 'sendConfirmEmail' => 'appartenances#invite'
  post 'appartenances/createList' => 'appartenances#createList'

  resources :epreuves
  get 'matieres/:matiere_id/epreuves' => 'epreuves#index_by', :as => 'epreuves_by_matiere'
  post 'epreuves/set_matiere' => 'epreuves#set_matiere'

  get 'resultats/create' => 'resultats#create'
  get 'epreuves/:epreuve_id/resultats' => 'resultats#show', :as => 'resultats_show'
  post 'resultats/update' => 'resultats#update', :as => 'resultats_update'
  
  

end

app/models/epreuve.rb
class Epreuve < ActiveRecord::Base
	belongs_to	:matiere
	has_many :resultats

	after_save :create_results

	def create_results
		if (appartenances = self.matiere.appartenances)
			appartenances.each do |a|
				Resultat.create(:epreuve_id => self.id, :etudiant_id => a.etudiant_id)
			end
		end
	end
end

app/controllers/epreuves_controller.rb
class EpreuvesController < ApplicationController
  before_action :set_epreuve, only: [:show, :edit, :update, :destroy]

  # GET /epreuves
  # GET /epreuves.json
  def index
    if isConnected?
      @utilisateur = current_user
      # session.delete([:current_matiere_id])
      if @utilisateur.type == 'Admin'
        @matieres = Matiere.all
      elsif @utilisateur.type == 'Enseignant'
        @matieres = @utilisateur.matieres
      else
        @matieres = Appartenance.getMatieresFromEtu(@utilisateur.id)
      end
    else
      redirect_to root_path
    end
  end

  def index_by
    if isConnected?
      @matiere = Matiere.find(params[:matiere_id])
    else
      redirect_to root_path
    end
  end

  # GET /epreuves/1
  # GET /epreuves/1.json
  def show
  end

  # GET /epreuves/new
  def new
    @epreuve = Epreuve.new
    @matiere = current_matiere
    @epreuve.matiere_id = @matiere.id
  end

  def set_matiere
    session[:current_matiere_id] = params[:matiere_id]
    redirect_to new_epreuve_path
  end

  # GET /epreuves/1/edit
  def edit
  end

  # POST /epreuves
  # POST /epreuves.json
  def create
    @epreuve = Epreuve.new(epreuve_params)

    respond_to do |format|
      if @epreuve.save
        session[:current_epreuve_id] = @epreuve.id
        format.html { redirect_to epreuves_path }
        format.json { render :show, status: :created, location: @epreuve }
      else
        format.html { render :new }
        format.json { render json: @epreuve.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /epreuves/1
  # PATCH/PUT /epreuves/1.json
  def update
    respond_to do |format|
      if @epreuve.update(epreuve_params)
        format.html { redirect_to epreuves_path, alert: 'Vos modifications ont bien été prises en compte.' }
        format.json { render :show, status: :ok, location: epreuves_path }
      else
        format.html { render :index }
        format.json { render json: @epreuve.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epreuves/1
  # DELETE /epreuves/1.json
  def destroy
    @epreuve.resultats.each do |res|
      res.destroy
    end
    @epreuve.destroy
    respond_to do |format|
      format.html { redirect_to epreuves_url, alert: 'Votre épreuve a bien été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_epreuve
      @epreuve = Epreuve.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def epreuve_params
      allow = [:titre, :date, :matiere_id]
      params.require(:epreuve).permit(allow)
    end
end

app/helpers/epreuves_helper.rb
module EpreuvesHelper
end

app/views/epreuves/_form.html.erb
<%= form_for(@epreuve) do |f| %>
  <% if @epreuve.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@epreuve.errors.count, "error") %> prohibited this epreuve from being saved:</h2>

      <ul>
      <% @epreuve.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <table>
      <tr><td><label for="epreuve_titre">Nom de l'épreuve</label><br>
      <%= text_field 'epreuve', 'titre' %></tr></td>
      <tr><td><label for="epreuve_date">Date de l'épreuve</label><br>
      <%= date_field 'epreuve', 'date' %></tr></td>
      <%= hidden_field 'epreuve', 'matiere_id' %>
    </table>
    <%= f.submit %>
  </div>
<% end %>

app/views/epreuves/edit.html.erb
<h1>Editing epreuve</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @epreuve %> |
<%= link_to 'Retour', epreuves_path %>

app/views/epreuves/index.html.erb
<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<h1>Choisissez votre épreuve</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr class="header">
        <th>Matière</th>
        <th>Titre</th>
        <th>Date</th>
        <th>Actions</th>
        <td></td>
        <td></td>
      </tr>
      <% @matieres.each do |mat| %>
      <tr>
        <tr>
          <th class="majuscule"><%= mat.titre %></th>
        </tr>
        <% mat.epreuves.each do |epreuve| %>
          <tr>
            <td></td>
            <th><a href=<%= resultats_show_path(epreuve.id) %>><%= epreuve.titre %></a></th>
            <td><%= epreuve.date.strftime("%d-%m-%Y") %></td>
            <% if current_user.type != 'Etudiant' %>
            <td><%= link_to 'Modifier', edit_epreuve_path(epreuve) %> | <%= link_to 'Supprimer', epreuve, method: :delete, data: { confirm: 'Etes vous sûr ?' } %></td>
            <% end %>
          </tr>
        <% end %>
        <tr class="header">
          <td>
            <% if current_user.type != 'Etudiant' %>
              <%= link_to 'Créer une nouvelle épreuve', epreuves_set_matiere_path(:matiere_id => mat.id), method: :post %>
            <% end %>
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tr>
      <% end %>
  </tbody>
</table>

<br>

app/views/epreuves/index_by.html.erb
<p id="notice"><%= notice %></p>

<h1>Choisissez votre épreuve</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr class="header">
        <th>Matière</th>
        <th>Titre</th>
        <th>Date</th>
        <th>Actions</th>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <th><%= @matiere.titre %></th>
      </tr>
    <% @matiere.epreuves.each do |epreuve| %>
      <tr>
        <td></td>
        <th><a href=<%= resultats_show_path(epreuve.id) %>><%= epreuve.titre %></a></th>
        <td><%= epreuve.date.strftime("%d-%m-%Y") %></td>
        <td><%= link_to 'Modifier', edit_epreuve_path(epreuve) %></td>
        <td><%= link_to 'Supprimer', epreuve, method: :delete, data: { confirm: 'Êtes-vour sûr ?' } %></td>         
      </tr>
    <% end %>
    <tr>
      <td><%= link_to 'Créer une nouvelle épreuve', new_epreuve_path %></td>
    </tr>
  </tbody>
</table>
<br>

app/views/epreuves/new.html.erb
<h1>Ajouter une nouvelle épreuve pour <%= @matiere.titre %></h1>

<%= render 'form' %>

<%= link_to 'Retour', epreuves_path %>

app/views/epreuves/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_epreuve_path(@epreuve) %> |
<%= link_to 'Retour', epreuves_path %>