config/routes.rb
Rails.application.routes.draw do

  root 'utilisateurs#index'

  resources :utilisateurs
  post 'connexion' => 'utilisateurs#login'
  get 'deconnexion' => 'utilisateurs#logout'
  get 'changePassword' => 'utilisateurs#change_password'
  post 'submitNewPassword' => 'utilisateurs#submit_password_change'
  get '/list' => 'utilisateurs#list', :as => 'utilisateurs_list'
  get 'confirm/:id' => 'utilisateurs#confirm', :as => 'utilisateurs_confirm'
  get 'confirm_admin/:id' => 'utilisateurs#confirm_admin'
  get 'enseignants' => 'utilisateur#index'
  get 'etudiants' => 'utilisateurs#index'

  resources :matieres
  get 'add_etu' => 'matieres#add_student'
  post 'submit_etu' => 'matieres#submit_student'

  get 'sendConfirmEmail' => 'appartenances#invite'
  post 'appartenances/createList' => 'appartenances#createList'

  resources :epreuves
  get 'matieres/:matiere_id/epreuves' => 'epreuves#index_by', :as => 'epreuves_by_matiere'
  post 'epreuves/set_matiere' => 'epreuves#set_matiere'

  get 'resultats/create' => 'resultats#create'
  get 'epreuves/:epreuve_id/resultats' => 'resultats#show', :as => 'resultats_show'
  post 'resultats/update' => 'resultats#update', :as => 'resultats_update'
  
  

end

app/models/matiere.rb
class Matiere < ActiveRecord::Base
	belongs_to :enseignants
	has_many :epreuves
	has_many :appartenances

	validates :enseignant_id, :presence => true
	validates :titre, :presence => true
	validates :debut, :presence => true
	validates :fin, :presence => true
end

app/controllers/matieres_controller.rb
class MatieresController < ApplicationController
  before_action :set_matiere, only: [:show, :edit, :update, :destroy]

  # GET /matieres
  # GET /matieres.json
  def index
    if isConnected?
      @user = current_user
      if @user.type == 'Admin'
        @matieres = Matiere.all
      elsif @user.type == 'Enseignant'
        @matieres = @user.matieres
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  # GET /matieres/1
  # GET /matieres/1.json
  def show
    @utilisateur = current_user
    session[:current_matiere_id] = @matiere.id
  end

  # GET /matieres/new
  def new
    @matiere = Matiere.new
    @utilisateur = current_user
    if @utilisateur.type != 'Admin'
      @matiere.enseignant_id = @utilisateur.id
    end
  end

  # GET /matieres/1/edit
  def edit
    @utilisateur = current_user
  end

  # POST /matieres
  # POST /matieres.json
  def create
    @matiere = Matiere.new(matiere_params)
    # @matiere.enseignant_id = current_user.id
    respond_to do |format|
      if @matiere.save
        format.html { redirect_to matieres_path, alert: 'Matière créée.' }
        format.json { render :show, status: :created, location: @matiere }
      else
        format.html { render :new }
        format.json { render json: @matiere.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matieres/1
  # PATCH/PUT /matieres/1.json
  def update
    respond_to do |format|
      if @matiere.update(matiere_params)
        format.html { redirect_to @matiere, alert: 'La matière a été mise à jour.' }
        format.json { render :show, status: :ok, location: @matiere }
      else
        format.html { render :edit }
        format.json { render json: @matiere.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matieres/1
  # DELETE /matieres/1.json
  def destroy
    @matiere.appartenances.each do |a|
      a.destroy
    end
    @matiere.epreuves.each do |e|
      e.destroy
    end
    @matiere.destroy
    respond_to do |format|
      format.html { redirect_to matieres_url, notice: 'La matière a bien été supprimée.' }
      format.json { head :no_content }
    end
  end

  def add_student
    already_in = Appartenance.getIdsInMatiere(current_matiere.id)
    if already_in.count != 0
      @etudiants = Etudiant.where("id NOT IN (?)", already_in).sort_by{|etu| etu.nom}
    else
      @etudiants = Etudiant.all
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matiere
      @matiere = Matiere.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matiere_params
      allow = [:titre, :debut, :fin, :description, :enseignant_id]
      params.require(:matiere).permit(allow)
    end
end

app/helpers/matieres_helper.rb
module MatieresHelper
end

app/views/matieres/_form.html.erb
<%= form_for(@matiere) do |f| %>
  <% if @matiere.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@matiere.errors.count, "error") %> prohibited this matiere from being saved:</h2>

      <ul>
      <% @matiere.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <table>
    <tr><td><label for="matiere_title">Titre: </label><br>
    <%= text_field 'matiere', 'titre' %></tr></td>
    <tr><td><label for="matiere_debut">Date de début: </label><br>
    <%= date_field 'matiere', 'debut' %></tr></td>
    <tr><td><label for="matiere_fin">Date de fin: </label><br>
    <%= date_field 'matiere', 'fin' %></tr></td>
    <tr><td><label for="matiere_description">Description: </label><br>
    <%= text_area 'matiere', 'description' %></tr></td>
    <% if @utilisateur.type == 'Admin' %>
      <p><label for="matiere_enseignant_id">Enseignant responsable: </label>
      <%= collection_select(:matiere, :enseignant_id, Enseignant.all, :id, :fullname) %></p>
    <% else %>
      <%= hidden_field 'matiere', 'enseignant_id' %>
    <% end %>
    </table>
    <%= f.submit 'Valider' %>
    
  </div>
<% end %>

app/views/matieres/add_student.html.erb
<h1>Choisissez un étudiant parmi la liste</h1>
<p id="notice"> <%= notice %> </p>
<table>
	<tr class="header">
		<th>Nom</th>
		<th>Prénom</th>
		<th><%= check_box_tag "check_all", "", false, :onclick => "checkAllCbs(this);"%>  Ajouter</th>
	</tr>
<%= form_tag(appartenances_createList_path) do %>
<% @etudiants.each do |etu| %>
	<tr>
		<td><%= etu.nom %></td>
		<td><%= etu.prenom %></td>
		<td><%= check_box_tag "checked[]", "#{etu.id}", false %></td>
	</tr>
<% end %>	
</table>		
<%= submit_tag 'Valider' %>
<% end %>
<div class="center">
	<h3>OU</h3>
	<%= link_to 'Inviter un nouvel étudiant', new_utilisateur_path(:type => 'Etudiant') %>
</div>

app/views/matieres/edit.html.erb
<h1>Editing Matiere</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @matiere %> |
<%= link_to 'Retour', matieres_path %>

app/views/matieres/index.html.erb
<p id="notice"><%= notice %></p>
<p id="matiere"><%= alert %></p>

<h1>Listes des matières</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
      <tr class="header">
        <th>Titre</th>
        <th>Description</th>
        <th>Début</th>
        <th>Fin</th>
        <th>Actions</th>
      </tr>
    <% @matieres.each do |matiere| %>
      <a href=<%= matiere_path(matiere.id) %>></a>
      <tr>
        <td class="majuscule"><FONT size="3pt"><strong><a href=<%= matiere_path(matiere.id) %>><%= matiere.titre %></a></strong></FONT></td>
        <td><%= matiere.description%></td>
        <td><%= matiere.debut.strftime("%d-%m-%Y") %></td>
        <td><%= matiere.fin.strftime("%d-%m-%Y")%></td>
        <td><%= link_to 'Supprimer', matiere, method: :delete, data: { confirm: 'Etes vous sûr ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouvelle matière', new_matiere_path %>

app/views/matieres/new.html.erb
<h1>Nouvelle matière</h1>

<%= render 'form' %>




<%= link_to 'Retour', matieres_path %>

app/views/matieres/show.html.erb
<p id="notice"><%= notice %></p>
<table class="tab">
	<tr>
		<td class="majuscule"><FONT size="20pt"><strong><%= @matiere.titre %></strong></FONT></td>
	</tr>
	<tr>
		<td><%= @matiere.description %></td>
	</tr>
</table>
<div class="center">
	<%= link_to 'Ajouter un étudiant', add_etu_path %>  |
	<%= link_to 'Voir les épreuves pour cette matière', epreuves_by_matiere_path(:matiere_id => @matiere.id) %> | 
	<%= link_to 'Modifier', edit_matiere_path(@matiere) %>  |
	<%= link_to 'Retour', matieres_path %>
</div>